apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgresql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-postgresql
  template:
    metadata:
      labels:
        app: gitea-postgresql
    spec:
      containers:
        - name: gitea-postgresql
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: gitea
            - name: POSTGRES_USER
              value: gitea
            - name: POSTGRES_PASSWORD
              value: gitea
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: perviyyegor/gitea-docker-repo:latest
          imagePullPolicy: IfNotPresent
          
          livenessProbe:
            tcpSocket:
              port: 3000
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: gitea-data
              mountPath: /home/git/app/data
      securityContext:
        fsGroup: 1000
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data-pvc